/* FORM Coach precision refinements — primary sets + muscle mapping */
(()=>{
function pSets(ex){const all=(ex?.setData||[]).filter(s=>s&&s.setType!=='warmup'&&Number(s.weight)>0&&Number(s.reps)>0),primary=all.filter(s=>!s.setType||s.setType==='working');return primary.length?primary:all}
function allSets(ex){return (ex?.setData||[]).filter(s=>s&&s.setType!=='warmup'&&Number(s.weight)>0&&Number(s.reps)>0)}
function muscle(name){const n=String(name||'').toLowerCase();if(/squat|leg press|hack|bulgarian/.test(n))return'quads';if(/romanian|leg curl/.test(n))return'hamstrings';if(/shoulder|lateral|reverse pec/.test(n))return'shoulders';if(/chest|fly|press/.test(n))return'chest';if(/pulldown|row|lat /.test(n)||n.startsWith('lat'))return'back';if(/triceps/.test(n))return'triceps';if(/curl/.test(n))return'biceps';if(/calf/.test(n))return'calves';if(/crunch|knee.*raise|leg raise/.test(n))return'abs';return'other'}
const labels={chest:'Göğüs',back:'Sırt',shoulders:'Omuz',quads:'Quadriceps',hamstrings:'Hamstring',biceps:'Biceps',triceps:'Triceps',calves:'Baldır',abs:'Karın'};
function parseRange(x){const m=String(x||'').match(/(\d+)\s*[-–]\s*(\d+)/);if(m)return[Number(m[1]),Number(m[2])];const n=Number(String(x||'').match(/\d+/)?.[0]||0);return[n||8,n||12]}
function f(v,d=1){return Number(v||0).toLocaleString('tr-TR',{maximumFractionDigits:d})}
function snap(v){return Math.round(v*2)/2}
function step(name,weight){return /lateral|curl|triceps|fly/i.test(name)?(weight<15?1:2):2.5}
function readinessLow(){const r=db.coach?.readiness?.[today];if(!r||!Number(r.sleep)||!Number(r.energy)||!Number(r.soreness))return false;const score=Math.round(Math.min(1,Number(r.sleep)/7.5)*40+(Number(r.energy)/5)*35+((6-Number(r.soreness))/5)*25);return score<55}
function refinedRec(name,repRange,type){const hist=(db.workouts||[]).filter(w=>w.type===type&&(w.exercises||[]).some(e=>e.name===name));const ex=hist.slice(-1)[0]?.exercises?.find(e=>e.name===name);if(!ex)return{tone:'neutral',title:'İlk referansı oluştur',text:'Bugünkü çalışma setlerini kaydet; sonraki seansta FORM ana setlere göre yük önerisi verecek.'};const sets=pSets(ex);if(!sets.length)return{tone:'neutral',title:'Referans set bekleniyor',text:'Progressive overload için kg ve tekrar içeren en az bir çalışma seti gerekli.'};const [min,max]=parseRange(repRange),base=Math.max(...sets.map(s=>Number(s.weight))),reps=sets.map(s=>Number(s.reps)),rirs=sets.map(s=>Number(s.rir)).filter(Number.isFinite),avgRir=rirs.length?rirs.reduce((a,b)=>a+b,0)/rirs.length:null,allMax=reps.every(r=>r>=max),low=reps.some(r=>r<Math.max(1,min-1));let target=base,tone='neutral',title='Aynı kiloyu koru',text=`Ana setler: ${sets.map(s=>`${s.weight}×${s.reps}`).join(' • ')}`;if(allMax&&(avgRir==null||avgRir>=1)){target=snap(base+step(name,base));tone='good';title=`${f(target,1)} kg dene`;text=`Ana çalışma setleri ${max}+ tekrara ulaştı. Küçük ve kontrollü yük artışı öneriliyor.`}else if(low){target=snap(base*.95);tone='mid';title=`${f(target,1)} kg civarı`;text='Ana çalışma setlerinden biri hedef tekrar bandının belirgin altında. Önce temiz tekrarları geri kazan.'}else{text=`${f(base,1)} kg ile toplam tekrarı artır; ana setleri ${max} tekrara yaklaştır.`}if(readinessLow()&&target){target=snap(target*.95);tone='mid';title=`Toparlanma: ${f(target,1)} kg`;text='Bugünkü hazırlık düşük. Normal progressive hedef yerine yaklaşık %5 daha kontrollü yük kullan.'}return{tone,title,text,target}}
function refineRecommendations(){const type=window._wk||Object.keys(db.program||{})[0],rows=(db.program?.[type]||[]).map(e=>typeof normalizeExercise==='function'?normalizeExercise(e):e),cards=[...document.querySelectorAll('.workout-card')];rows.forEach((e,i)=>{const block=cards[i]?.querySelector('.coach-load');if(!block)return;const r=refinedRec(e.name,e.reps,type);block.className=`coach-load ${r.tone}`;block.innerHTML=`<div><span>Sonraki hedef</span><strong>${r.title}</strong><small>${r.text}</small></div>${r.target?`<button class="secondary small" onclick="coachApplyLoad(${i},${r.target})">Kg’yi uygula</button>`:''}`})}
function weekStart(){const d=new Date();d.setHours(0,0,0,0);const delta=(d.getDay()+6)%7;d.setDate(d.getDate()-delta);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function refineMuscles(){const grid=document.querySelector('.coach-muscle-grid');if(!grid)return;const start=weekStart(),done={},planned={};Object.values(db.settings?.trainingDays||{}).forEach(plan=>(db.program?.[plan]||[]).forEach(raw=>{const e=typeof normalizeExercise==='function'?normalizeExercise(raw):raw,m=muscle(e.name);if(m!=='other')planned[m]=(planned[m]||0)+Number(e.sets||0)}));(db.workouts||[]).filter(w=>w.date>=start).forEach(w=>(w.exercises||[]).forEach(e=>{const m=muscle(e.name);if(m!=='other')done[m]=(done[m]||0)+allSets(e).length}));grid.innerHTML=Object.keys(planned).map(m=>{const p=planned[m]||0,d=done[m]||0,pc=p?Math.min(110,d/p*100):0;return `<div><div><span>${labels[m]}</span><b>${d}/${p} set</b></div><i><em style="width:${pc}%"></em></i></div>`}).join('')}
window.coachApplyLoad=function(i,w){const card=document.querySelectorAll('.workout-card')[i];if(!card)return;card.querySelectorAll('tbody tr').forEach(tr=>{const type=tr.querySelector('.set-type-select')?.value||'working';if(type==='working'){const input=tr.querySelector('input[id^="kg_"]');if(input)input.value=w}});if(typeof toast==='function')toast(`${f(w,1)} kg ana setlere uygulandı`)};
function refine(){refineRecommendations();refineMuscles()}
const base=window.renderWorkout;if(base)window.renderWorkout=function(){base();setTimeout(refine,90)};
setTimeout(()=>{if(document.querySelector('.workout-card'))refine()},120);
})();
