(()=>{
'use strict';
const FILTERS=['Tümü','Protein','Karbonhidrat','Meyve','Sebze','İçecek'];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const norm=s=>String(s||'').toLocaleLowerCase('tr-TR');
function favorites(){const usage=db.settings?.foodUsage||{};return db.foods.map((f,i)=>({f,i,n:Number(usage[f.name]||0)})).sort((a,b)=>b.n-a.n||a.i-b.i).slice(0,6)}
function visual(f){const n=norm(f.name),c=norm(f.category);if(n.includes('orman')||n.includes('yaban')||n.includes('frambuaz')||n.includes('böğürtlen'))return['🫐','tone-berry'];if(n.includes('yulaf'))return['🥣','tone-oat'];if(n.includes('muz'))return['🍌','tone-banana'];if(n.includes('tavuk')||n.includes('hindi'))return['🍗','tone-protein'];if(n.includes('pirinç')||n.includes('bulgur')||n.includes('kinoa'))return['🍚','tone-rice'];if(n.includes('yumurta'))return['🥚','tone-egg'];if(n.includes('yoğurt')||n.includes('süt')||n.includes('kefir')||n.includes('ayran'))return['🥛','tone-dairy'];if(c.includes('meyve'))return['🍓','tone-fruit'];if(c.includes('balık'))return['🐟','tone-protein'];if(c.includes('et')||c.includes('sporcu'))return['🥩','tone-protein'];if(c.includes('ekmek'))return['🍞','tone-oat'];if(c.includes('kuruyemiş'))return['🥜','tone-oat'];return['🍽️','tone-default']}
function quickHTML(){return `<section class="nutrition-quick-section"><div class="nutrition-quick-head"><h3>Hızlı ekle</h3><p>Sık eklediğin besinleri tek dokunuşla ekle.</p></div><div class="nutrition-quick-grid">${favorites().map(({f,i})=>{const [icon,tone]=visual(f);return `<button class="nutrition-quick-tile ${tone}" type="button" onclick="openFoodAdder(${i})"><span class="nutrition-quick-icon" aria-hidden="true">${icon}</span><span class="nutrition-quick-copy"><strong>${esc(f.name)}</strong><small>${typeof fmt==='function'?fmt(f.kcal):Math.round(Number(f.kcal)||0)} kcal /100g</small></span><span class="nutrition-quick-plus">+</span></button>`}).join('')}</div></section>`}
function filterHTML(){const active=window._nutritionFilter||'Tümü';return `<section class="nutrition-filter-section"><h3 class="nutrition-filter-title">Filtrele</h3><div class="nutrition-filter-grid">${FILTERS.map(x=>`<button type="button" class="nutrition-filter-btn ${active===x?'active':''}" onclick="ftSetNutritionFilter('${x}')">${x}</button>`).join('')}</div></section>`}
function filterMatch(f,filter){if(filter==='Tümü')return true;const n=norm(f.name),c=norm(f.category),unit=norm(f.unit);if(filter==='Protein')return c.includes('et & tavuk')||c.includes('balık')||c.includes('yumurta & süt')||c.includes('sporcu')||/(tavuk|hindi|dana|kuzu|somon|ton balığı|yumurta|whey|protein|lor|peynir|skyr)/.test(n);if(filter==='Karbonhidrat')return c.includes('tahıl')||c.includes('ekmek')||/(pirinç|yulaf|bulgur|makarna|kinoa|patates|lavaş|granola|müsli)/.test(n);if(filter==='Meyve')return c.includes('meyve');if(filter==='Sebze')return c.includes('sebze')||/(brokoli|ıspanak|domates|salatalık|avokado|bezelye|mısır)/.test(n);if(filter==='İçecek')return unit.includes('bardak')||/(süt|kefir|ayran|su|kahve|çay)/.test(n);return true}
function resultRows(){const q=norm(document.getElementById('diarySearch')?.value||'').trim(),filter=window._nutritionFilter||'Tümü',usage=db.settings?.foodUsage||{};let rows=db.foods.map((f,i)=>({f,i,n:Number(usage[f.name]||0)})).filter(({f})=>filterMatch(f,filter));if(q)rows=rows.filter(({f})=>norm(`${f.name} ${f.brand||''} ${f.category||''}`).includes(q));else rows=rows.sort((a,b)=>b.n-a.n||a.i-b.i).slice(0,18);return rows.slice(0,45)}
function renderResults(){const box=document.getElementById('diaryResults');if(!box)return;const rows=resultRows();box.innerHTML=rows.map(({f,i})=>`<button class="diary-result" onclick="openFoodAdder(${i})"><span><strong>${esc(f.name)}</strong><small>${f.brand&&f.brand!=='Genel'?esc(f.brand)+' • ':''}${esc(f.category||'Diğer')} • ${typeof fmt==='function'?fmt(f.kcal):Math.round(Number(f.kcal)||0)} kcal /100g</small></span><span class="diary-add">+</span></button>`).join('')||'<div class="muted" style="padding:10px">Eşleşen besin bulunamadı.</div>'}
window.ftSetNutritionFilter=function(filter){window._nutritionFilter=FILTERS.includes(filter)?filter:'Tümü';document.querySelectorAll('.nutrition-filter-btn').forEach(b=>b.classList.toggle('active',b.textContent.trim()===window._nutritionFilter));renderResults()};
window.formFoodSearch=function(){renderResults()};
function install(){const shell=document.querySelector('.nutri-shell');if(!shell)return;const card=[...shell.querySelectorAll('.card')].find(x=>x.querySelector('h2')?.textContent?.trim()==='Besin ekle');if(!card)return;const rails=[...card.querySelectorAll('.quick-favs')];if(rails[0])rails[0].outerHTML=quickHTML();else if(!card.querySelector('.nutrition-quick-section'))card.querySelector('.diary-toolbar')?.insertAdjacentHTML('afterend',quickHTML());const railsAfter=[...card.querySelectorAll('.quick-favs')];if(railsAfter[0])railsAfter[0].outerHTML=filterHTML();else if(!card.querySelector('.nutrition-filter-section'))card.querySelector('.nutrition-quick-section')?.insertAdjacentHTML('afterend',filterHTML());renderResults()}
window._nutritionFilter=window._nutritionFilter||'Tümü';
const base=window.renderNutrition;if(typeof base==='function'){window.renderNutrition=function(...args){const out=base.apply(this,args);setTimeout(install,0);return out}}
setTimeout(install,40);
})();