/* FORM workout UI v2 — today first, everything one tap away */
(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=r=>{try{return normalizeExercise(r)}catch{return r||{}}};
function rows(){return (db.program?.[window._wk]||[]).map(norm)}
function history(name,n=8){return (db.workouts||[]).filter(w=>w.exercises?.some(e=>e.name===name)).sort((a,b)=>String(a.date).localeCompare(String(b.date))).slice(-n).map(w=>({date:w.date,e:w.exercises.find(e=>e.name===name)}))}
function sets(e){return (e?.setData||[]).filter(x=>x.done||x.weight||x.reps)}
function summary(e){const s=sets(e);if(!s.length)return'—';return s.map(x=>`${x.weight?`${Number(x.weight).toLocaleString('tr-TR',{maximumFractionDigits:1})} kg × `:''}${x.reps||'—'}`).join(' / ')}
function best(e){const s=sets(e);if(!s.length)return'—';const x=s.reduce((a,b)=>((+b.weight||0)*(+b.reps||0)>(+a.weight||0)*(+a.reps||0)?b:a),s[0]);return x.weight?`${x.weight} kg × ${x.reps||0}`:`${x.reps||0} tekrar`}
window.ftQuickHistory=i=>{const e=rows()[i];if(!e)return;const h=history(e.name,20);document.getElementById('ftQuickHistoryModal')?.remove();const m=document.createElement('div');m.id='ftQuickHistoryModal';m.className='ftiq-modal';m.innerHTML=`<div class="ftiq-sheet"><div class="ftiq-head"><div><h3>${esc(e.name)}</h3><div class="ftiq-mini">Geçmiş antrenmanlar</div></div><button class="secondary small" onclick="ftQuickHistoryModal.remove()">Kapat</button></div><div class="ftiq-list">${h.slice().reverse().map(x=>`<div class="ftiq-row"><b>${esc(x.date)}</b><span>${esc(summary(x.e))}</span><span class="ftiq-mini">En iyi: ${esc(best(x.e))}</span></div>`).join('')||'<div class="ftiq-mini">Henüz kayıt yok.</div>'}</div></div>`;document.body.appendChild(m)};
function addInlineHistory(){document.querySelectorAll('.workout-card').forEach((card,i)=>{if(card.querySelector('.ft-inline-history'))return;const e=rows()[i],h=history(e?.name,2),last=h.at(-1),prev=h.at(-2);const box=document.createElement('div');box.className='ft-inline-history';box.innerHTML=`<div><b>Son:</b> ${esc(last?summary(last.e):'İlk kayıt')}</div>${prev?`<div><b>Önceki:</b> ${esc(summary(prev.e))}</div>`:''}<div class="ft-inline-history-actions"><button class="secondary small" onclick="ftQuickHistory(${i})">Geçmiş / PR</button><button class="secondary small" onclick="ftIQReplace?.(${i},'${String(e?.name||'').replace(/'/g,"\\'")}')">Değiştir</button></div>`;const head=card.querySelector('.exercise-head');head?.insertAdjacentElement('afterend',box)})}
function quickBar(){if(document.getElementById('ftWorkoutQuickbar'))return;const first=document.querySelector('.workout-card');if(!first)return;const q=document.createElement('div');q.id='ftWorkoutQuickbar';q.className='ft-workout-quickbar';q.innerHTML='<button class="primary" onclick="formStartWorkout?.()">▶ Başlat</button><button onclick="document.getElementById(\'formExerciseSelector\')?.scrollIntoView({behavior:\'smooth\',block:\'center\'})">Hareketler</button><button onclick="ftLibraryOpenAdd?.()">+ Hareket</button>';first.parentElement?.insertBefore(q,first)}
function compactPicker(){const sel=[...document.querySelectorAll('select')].find(s=>[...s.options].some(o=>db.program?.[o.value]||db.program?.[o.text]));if(!sel||sel.closest('.ft-workout-compact-picker'))return;const holder=sel.closest('div');if(!holder)return;const wrap=document.createElement('div');wrap.className='ft-workout-compact-picker';wrap.innerHTML='<label>ANTRENMAN</label>';holder.parentNode.insertBefore(wrap,holder);wrap.appendChild(sel);holder.querySelector('.ft-schedule-badge')?.remove();const lab=holder.querySelector('label');if(lab)lab.style.display='none'}
function enhance(){compactPicker();quickBar();addInlineHistory()}
const base=window.renderWorkout;window.renderWorkout=function(){base();setTimeout(enhance,40)};
setTimeout(enhance,120);
})();
