(()=>{
const focusByPlan={};
const SET_TYPES=[['warmup','Isınma'],['working','Working'],['backoff','Back-off'],['drop','Drop set']];
function selectedPlan(){return window._wk||Object.keys(db.program||{})[0]||''}
function planRows(){return (db.program?.[selectedPlan()]||[]).map(normalizeExercise)}
function currentIndex(){const rows=planRows(),raw=Number(focusByPlan[selectedPlan()]||0);return Math.max(0,Math.min(Math.max(0,rows.length-1),raw))}
function setFocus(index,scroll=true){const rows=planRows();if(!rows.length)return;focusByPlan[selectedPlan()]=Math.max(0,Math.min(rows.length-1,index));saveFocusedFields();applyWorkoutFocus();if(scroll)setTimeout(()=>document.getElementById('formCurrentExercise')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
function actualSetCount(i){return document.querySelectorAll(`#settable_${i} tbody tr`).length||planRows()[i]?.sets||0}
function setProgress(i){const card=document.querySelectorAll('.workout-card')[i];if(!card)return{done:false,partial:false,total:0,checked:0};const checks=[...card.querySelectorAll('.set-done input[type="checkbox"]')],checked=checks.filter(x=>x.checked).length;return{done:checks.length>0&&checked===checks.length,partial:checked>0&&checked<checks.length,total:checks.length,checked}}
function selectorHTML(){const rows=planRows(),active=currentIndex();return `<div class="form-exercise-selector" id="formExerciseSelector"><div class="form-selector-head"><b>Programdaki hareketler</b><span>İsme dokunarak geç</span></div><div class="form-selector-list">${rows.map((e,i)=>{const p=setProgress(i),state=i===active?'active':p.done?'done':p.partial?'partial':'';const label=i===active?'Şu an':p.done?'Tamamlandı':p.partial?`${p.checked}/${p.total} set`:'Aç';return `<button class="form-selector-btn ${state}" onclick="formSelectExercise(${i})"><span class="form-selector-num">${p.done?'✓':i+1}</span><span class="form-selector-name"><b>${e.name}</b><small>${actualSetCount(i)} set • ${e.reps} tekrar</small></span><span class="form-selector-state">${label}</span></button>`}).join('')}</div></div>`}
function applyWorkoutFocus(){const rows=planRows(),cards=[...document.querySelectorAll('.workout-card')];if(!rows.length||cards.length<rows.length)return;const active=currentIndex(),e=rows[active],pct=Math.round((active+1)/rows.length*100),wrap=cards[0].parentElement;if(!wrap)return;document.getElementById('formCurrentExercise')?.remove();document.getElementById('formExerciseSelector')?.remove();document.querySelector('.form-exercise-nav')?.remove();cards.forEach((card,i)=>{card.classList.toggle('form-active-exercise',i===active);card.classList.toggle('form-hidden-exercise',i!==active)});const banner=document.createElement('div');banner.id='formCurrentExercise';banner.className='form-exercise-focus';banner.innerHTML=`<div class="form-current-banner"><div><span>ŞU ANKİ HAREKET</span><b>${active+1} / ${rows.length} · ${e.name}</b></div><strong>%${pct}</strong></div><div class="form-workout-progress"><i style="width:${pct}%"></i></div>`;wrap.insertBefore(banner,cards[0]);const nav=document.createElement('div');nav.className='form-exercise-nav';nav.innerHTML=`<button class="secondary" onclick="formPrevExercise()" ${active===0?'disabled':''}>← Önceki</button><button class="form-next-exercise" onclick="formNextExercise()" ${active===rows.length-1?'disabled':''}>Sıradaki hareket →</button>`;cards[active].insertAdjacentElement('afterend',nav);wrap.insertAdjacentHTML('beforeend',selectorHTML())}
window.formSelectExercise=i=>setFocus(i);
window.formPrevExercise=()=>setFocus(currentIndex()-1);
window.formNextExercise=()=>setFocus(currentIndex()+1);

function previousType(exerciseIndex,setIndex){const last=db.workouts.filter(w=>w.type===selectedPlan()).slice(-1)[0],name=planRows()[exerciseIndex]?.name,ex=last?.exercises?.find(x=>x.name===name);return ex?.setData?.[setIndex]?.setType||'working'}
function typeSelect(i,j,selected){return `<select class="set-type-select" id="type_${i}_${j}" aria-label="Set tipi">${SET_TYPES.map(([v,l])=>`<option value="${v}" ${v===(selected||'working')?'selected':''}>${l}</option>`).join('')}</select>`}
function enhanceSetTables(){const cards=[...document.querySelectorAll('.workout-card')],rows=planRows();cards.slice(0,rows.length).forEach((card,i)=>{const head=card.querySelector('.exercise-head');if(head&&!head.querySelector('.form-set-stepper')){head.querySelector('button')?.remove();head.insertAdjacentHTML('beforeend',`<div class="form-set-stepper"><button class="secondary small" onclick="formRemoveSet(${i})">− Set</button><span id="setCount_${i}">${actualSetCount(i)}/5</span><button class="secondary small" onclick="formAddSet(${i})">＋ Set</button></div>`)}const table=card.querySelector(`#settable_${i}`);if(!table)return;const hr=table.querySelector('thead tr');if(hr&&!hr.querySelector('.set-type-head')){const th=document.createElement('th');th.className='set-type-head';th.textContent='TİP';hr.insertBefore(th,hr.children[1])} [...table.querySelectorAll('tbody tr')].forEach((tr,j)=>{if(tr.querySelector('.set-type-cell'))return;const td=document.createElement('td');td.className='set-type-cell';td.innerHTML=typeSelect(i,j,previousType(i,j));tr.insertBefore(td,tr.children[1])});updateSetCounter(i)})}
function updateSetCounter(i){const n=actualSetCount(i),e=document.getElementById(`setCount_${i}`);if(e)e.textContent=`${n}/5`;const card=document.querySelectorAll('.workout-card')[i];if(card){const buttons=card.querySelectorAll('.form-set-stepper button');if(buttons[0])buttons[0].disabled=n<=1;if(buttons[1])buttons[1].disabled=n>=5}const sel=document.getElementById('formExerciseSelector');if(sel)sel.outerHTML=selectorHTML()}
window.formAddSet=function(i){const tb=document.querySelector(`#settable_${i} tbody`);if(!tb)return;const j=tb.rows.length;if(j>=5){toast('Bir harekette en fazla 5 set ekleyebilirsin');return}const name=planRows()[i]?.name||'';const safe=name.replace(/'/g,"\\'");const tr=document.createElement('tr');tr.innerHTML=`<td class="set-num">${j+1}</td><td class="set-type-cell">${typeSelect(i,j,'working')}</td><td class="prev-cell">- × -</td><td><input id="kg_${i}_${j}" type="number" inputmode="decimal" step="0.5" placeholder="kg"></td><td><input id="rep_${i}_${j}" type="number" inputmode="numeric" step="1" placeholder="tekrar"></td><td><input id="rir_${i}_${j}" type="number" inputmode="decimal" step="0.5" placeholder="RIR"></td><td class="set-done"><input id="done_${i}_${j}" type="checkbox" onchange="setCompleted('${safe}',${j+1},this)"></td>`;tb.appendChild(tr);updateSetCounter(i)};
window.formRemoveSet=function(i){const tb=document.querySelector(`#settable_${i} tbody`);if(!tb)return;const n=tb.rows.length;if(n<=1){toast('En az 1 set kalmalı');return}tb.deleteRow(n-1);updateSetCounter(i)};
function saveFocusedFields(){/* Hareket geçişi DOM'u yeniden kurmadığı için alanlar yerinde kalır. */}

function pausedNow(){return !!window._workoutPauseAt}
function elapsedMs(){if(!window._workoutStart)return 0;const paused=Number(window._workoutPausedTotal)||0,current=pausedNow()?Date.now()-window._workoutPauseAt:0;return Math.max(0,Date.now()-window._workoutStart-paused-current)}
window.elapsedSeconds=()=>Math.floor(elapsedMs()/1000);
window.elapsedText=()=>{const t=elapsedSeconds(),h=Math.floor(t/3600),m=Math.floor((t%3600)/60),s=t%60;return [h,m,s].map(x=>String(x).padStart(2,'0')).join(':')};
window.startTimerTick=function(){clearInterval(window._timerInt);if(pausedNow())return;window._timerInt=setInterval(()=>{const e=document.getElementById('workoutTimer');if(e)e.textContent=elapsedText();else clearInterval(window._timerInt)},1000)};
window.formStartWorkout=function(){if(!window._workoutStart){window._workoutStart=Date.now();window._workoutPausedTotal=0;window._workoutPauseAt=null}else if(pausedNow()){window._workoutPausedTotal=(Number(window._workoutPausedTotal)||0)+(Date.now()-window._workoutPauseAt);window._workoutPauseAt=null}updateTimerControls();startTimerTick()};
window.formPauseWorkout=function(){if(!window._workoutStart||pausedNow())return;window._workoutPauseAt=Date.now();clearInterval(window._timerInt);updateTimerControls()};
window.formResetWorkoutTimer=function(){if(!window._workoutStart)return;if(!confirm('Antrenman sayacı sıfırlansın mı? Girdiğin kg, tekrar ve set kayıtları silinmez.'))return;clearInterval(window._timerInt);window._workoutStart=null;window._workoutPausedTotal=0;window._workoutPauseAt=null;const t=document.getElementById('workoutTimer');if(t)t.textContent='00:00:00';updateTimerControls()};
function timerControlsHTML(){return `<div class="form-workout-controls"><div class="form-workout-clock"><div class="muted">Antrenman süresi</div><div id="workoutTimer" class="timer">${window._workoutStart?elapsedText():'00:00:00'}</div></div><div class="form-timer-actions"><button id="formTimerStart" class="primary form-timer-start" onclick="formStartWorkout()">Başlat</button><button id="formTimerPause" class="form-timer-stop" onclick="formPauseWorkout()">Durdur</button><button class="form-timer-reset" onclick="formResetWorkoutTimer()">Sıfırla</button></div></div>`}
function updateTimerControls(){const s=document.getElementById('formTimerStart'),p=document.getElementById('formTimerPause');if(s){s.textContent=!window._workoutStart?'Başlat':pausedNow()?'Devam Et':'Çalışıyor';s.disabled=!!window._workoutStart&&!pausedNow()}if(p)p.disabled=!window._workoutStart||pausedNow();const t=document.getElementById('workoutTimer');if(t)t.textContent=window._workoutStart?elapsedText():'00:00:00'}
function installTimerControls(){const old=document.getElementById('startWorkoutBtn');if(!old)return;const row=old.closest('.card')?.querySelector('div[style*="justify-content:space-between"]');if(!row)return;row.outerHTML=timerControlsHTML();updateTimerControls();if(window._workoutStart&&!pausedNow())startTimerTick()}

const baseRenderWorkout=window.renderWorkout;
window.renderWorkout=function(){baseRenderWorkout();setTimeout(()=>{enhanceSetTables();installTimerControls();applyWorkoutFocus()},0)};
window.startWorkout=function(){formStartWorkout()};
window.saveWorkout=function(){if(!window._workoutStart){toast('Önce antrenmanı başlat');return}const type=window._wk;const ex=db.program[type].map((raw,i)=>{const e=normalizeExercise(raw),count=document.querySelectorAll(`#settable_${i} tbody tr`).length,setData=[];for(let j=0;j<count;j++){const kg=document.getElementById(`kg_${i}_${j}`)?.value,reps=document.getElementById(`rep_${i}_${j}`)?.value,rir=document.getElementById(`rir_${i}_${j}`)?.value,done=document.getElementById(`done_${i}_${j}`)?.checked,setType=document.getElementById(`type_${i}_${j}`)?.value||'working';if(kg||reps||done)setData.push({set:j+1,setType,weight:kg?Number(kg):null,reps:reps?Number(reps):null,rir:rir?Number(rir):null,done:!!done})}return{name:e.name,sets:e.sets,actualSets:count,repRange:e.reps,targetRir:e.rir,setData,note:document.getElementById(`note_${i}`)?.value||''}});const durationSec=elapsedSeconds(),cardio=cardioData();db.workouts.push({date:workoutDate.value,type,exercises:ex,durationSec,cardio});save();clearInterval(window._timerInt);clearInterval(window._restInt);window._restEnd=null;window._workoutStart=null;window._workoutPausedTotal=0;window._workoutPauseAt=null;focusByPlan[selectedPlan()]=0;toast(`Antrenman kaydedildi • ${Math.round(durationSec/60)} dk${cardio?` • kardiyo ~${cardio.kcal} kcal`:''}`);renderWorkout()};

document.addEventListener('change',e=>{if(e.target?.matches?.('.set-done input[type="checkbox"],.set-type-select'))setTimeout(()=>{const sel=document.getElementById('formExerciseSelector');if(sel)sel.outerHTML=selectorHTML()},30)});
setTimeout(()=>{if(document.querySelector('.workout-card')){enhanceSetTables();installTimerControls();applyWorkoutFocus()}},50);
})();